coffees/urls.py
from django.urls import path

from . import views

app_name = 'coffees'
urlpatterns = [
    # ex: /coffees/
    path('', views.index, name='index'),
    # ex: /coffees/1/
    path('<int:pk>/', views.show, name='show'),
    # ex: /coffees/add/
    path('add/', views.add, name='add'),
    # ex: /coffees/1/edit/
    path('<int:pk>/edit/', views.edit, name='edit'),
    # ex: /coffees/1/delete/
    path('<int:pk>/delete/', views.delete, name='delete'),
]

core/urls.py
from django.contrib import admin
from django.shortcuts import redirect
from utils.auth_views import register
from django.urls import path, include, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetConfirmView

login_params = {
    'template_name': 'users/login.html',
    'redirect_authenticated_user': True,
}

password_reset_params = {
    'template_name': 'users/password_reset.html',
    'email_template_name': 'users/password_reset/email.html',
    'subject_template_name': 'users/password_reset/subject.txt',
    'success_url': reverse_lazy('login'),
}

password_set_params = {
    'template_name': 'users/password_set.html',
    'post_reset_login': True,
    'success_url': reverse_lazy('login'),
}

urlpatterns = [
    path('', lambda request: redirect('coffees:index'), name='root'),
    path('login/', LoginView.as_view(**login_params), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path(
        'password-reset/',
        PasswordResetView.as_view(**password_reset_params),
        name='password_reset',
    ),
    path(
        'password-set/<uidb64>/<token>/',
        PasswordResetConfirmView.as_view(**password_set_params),
        name='password_set',
    ),
    path('coffees/', include('coffees.urls')),
    path('admin/', admin.site.urls),
]

handler403 = 'utils.error_handlers.permission_denied'
handler404 = 'utils.error_handlers.page_not_found'

coffees/models.py
from django.db import models


# Create your models here.
from utils.models import TimestampModel


class Roast(models.TextChoices):
    # enum = value(存入的值), display
    LIGHT = 'Light', '極淺度烘焙'
    CINNAMON = 'Cinnamon', '淺度烘焙'
    MEDIUM = 'Medium', '中度烘焙'
    HIGH = 'High', '中度微深烘焙'
    CITY = 'City', '中深度烘焙'
    FULL_CITY = 'Full-City', '微深度烘焙'
    FRENCH = 'French', '極深烘焙'
    ITALIAN = 'Italian', '極深度烘焙'


class OriginPlace(models.Model):
    name = models.CharField('名稱', max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '產地'  # 單數處理
        verbose_name_plural = '產地'  # 複數處理


class MainProcessing(models.Model):
    name = models.CharField('名稱', max_length=20, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '主要處理法'
        verbose_name_plural = '主要處理法'


class Grinding(TimestampModel):
    name = models.CharField('名稱', max_length=10, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = '磨豆方式'
        verbose_name_plural = '磨豆方式'


class Coffee(TimestampModel):
    name = models.CharField('名稱', max_length=20, unique=True)
    weight = models.PositiveIntegerField('重量')
    taste = models.TextField('味道')
    description = models.TextField('描述')
    roast = models.CharField('烘培程度', max_length=10, choices=Roast.choices)
    price = models.PositiveIntegerField('價格')
    discount = models.PositiveIntegerField('優惠價格')
    origin_place = models.ForeignKey(
        OriginPlace,
        on_delete=models.PROTECT,
        verbose_name='產地',
    )
    main_processing = models.ForeignKey(
        MainProcessing,
        on_delete=models.PROTECT,
        verbose_name='主要處理法',
    )

    grindings = models.ManyToManyField(Grinding, verbose_name='磨豆方式')

    def __str__(self):
        return f'{self.name}({self.price})'

    class Meta:
        verbose_name = '咖啡'
        verbose_name_plural = '咖啡'

utils/models.py
from django.db import models


class TimestampModel(models.Model):
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

coffees/forms.py
from django import forms

from .models import Coffee


class CoffeeForm(forms.ModelForm):
    class Meta:
        fields = '__all__'
        model = Coffee

utils/forms.py
from django import forms


class DeleteConfirmForm(forms.Form):
    check = forms.BooleanField(label='你確定要刪除嗎？')

coffees/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.http import HttpResponse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect

from utils.forms import DeleteConfirmForm
from .forms import CoffeeForm
from .models import Coffee


# Create your views here.
@login_required
def index(request):
    coffees = Coffee.objects.all()
    return render(request, 'coffees/index.html', {'coffees': coffees})


@login_required
def show(request, pk):
    coffee = get_object_or_404(Coffee, pk=pk)
    return render(request, 'coffees/show.html', {'coffee': coffee})


@login_required
@permission_required('coffees.add_coffee', raise_exception=True)
def add(request):
    form = CoffeeForm(request.POST or None)
    if form.is_valid():
        form.save()
        messages.success(request, '新增成功')
        return redirect('coffees:index')
    return render(request, 'coffees/add.html', {'form': form})


@login_required
@permission_required('coffees.edit_coffee', raise_exception=True)
def edit(request, pk):
    coffee = get_object_or_404(Coffee, pk=pk)
    form = CoffeeForm(request.POST or None, instance=coffee)
    if form.is_valid():
        form.save()
        messages.success(request, '更新成功')
        return redirect('coffees:index')
    return render(request, 'coffees/edit.html', {'form': form})


@login_required
@permission_required('coffees.delete_coffee', raise_exception=True)
def delete(request, pk):
    coffee = get_object_or_404(Coffee, pk=pk)
    form = DeleteConfirmForm(request.POST or None)
    if form.is_valid() and form.cleaned_data['check']:
        coffee.delete()
        messages.success(request, '刪除成功')
        return redirect('coffees:index')
    return render(request, 'coffees/delete.html', {'form': form})

templates/coffees/add.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>新增咖啡</h2>
        <hr>
        {% include 'share/_form.html' %}
    </div>
</div>
{% endblock %}

templates/coffees/delete.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>刪除咖啡</h2>
        <hr>
        {% include 'share/_form.html' %}
    </div>
</div>
{% endblock %}

templates/coffees/edit.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>更新咖啡</h2>
        <hr>
        {% include 'share/_form.html' %}
    </div>
</div>
{% endblock %}

templates/coffees/index.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col">
        {% if perms.coffees.add_coffee %}
        <a href="{% url 'coffees:add' %}"
           class="btn btn-outline-info float-right">
            新增咖啡
        </a>
        {% endif %}
        <h2>咖啡列表</h2>
        <hr>
        <table class="table table-striped">
            <thead>
            <tr>
                <th>#</th>
                <th>名稱</th>
                <th>烘培程度</th>
                <th>優惠價格</th>
            </tr>
            </thead>
            <tbody>
            {% for coffee in coffees %}
            <tr>
                <td>{{ coffee.id }}</td>
                <td>
                    <a href="{% url 'coffees:show' coffee.id %}">
                        {{ coffee.name }}
                    </a>
                </td>
                <td>{{ coffee.get_roast_display }}</td>
                <td>{{ coffee.discount }}</td>
            </tr>
            {% empty %}
            <tr>
                <td class="text-center" colspan="4">沒有咖啡～</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

templates/coffees/show.html
{% extends 'layout.html' %}

{% block main %}
{% if perms.coffees.delete_coffee %}
<a href="{% url 'coffees:delete' coffee.id %}"
   class="btn btn-danger float-right">
    刪除
</a>
{% endif %}
{% if perms.coffees.edit_coffee %}
<a href="{% url 'coffees:edit' coffee.id %}"
   class="btn btn-info float-right mr-2">
    編輯
</a>
{% endif %}
<h2>#{{ coffee.id }} {{ coffee.name }}</h2>
<hr>
<p>名稱: {{ coffee.name }}</p>
<p>重量: {{ coffee.weight }}</p>
<p>味道: {{ coffee.taste }}</p>
<p>描述: {{ coffee.description }}</p>
<p>烘培程度: {{ coffee.get_roast_display }}</p>
<p>價格: {{ coffee.price }}</p>
<p>優惠價格: {{ coffee.discount }}</p>
<p>產地: {{ coffee.origin_place }}</p>
<p>主要處理法: {{ coffee.main_processing }}</p>
<p>磨豆方式: {{ coffee.grindings.all | join:', ' }}</p>

<a href="{% url 'coffees:index' %}" class="btn btn-primary"><< 返回</a>
{% endblock %}

templates/layout.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>咖啡店</title>
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
          integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
          crossorigin="anonymous">
</head>

{% load bootstrap4 %}

<body>
{% include 'share/_navbar.html' %}

<div class="container my-3">
    <div class="row">
        <div class="col">
            <!-- 加上訊息顯示 -->
            {% bootstrap_messages %}
            {% block main %}{% endblock %}
        </div>
    </div>
</div>
</body>

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous">
</script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns"
        crossorigin="anonymous">
</script>

</html>

templates/share/_form.html
{% load bootstrap4 %}

<form action="" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-outline-info float-right">送出</button>
</form>

templates/share/_navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <a class="navbar-brand" href="{% url 'root' %}">咖啡店</a>

    <button class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarToggler"
            aria-controls="navbarToggler"
            aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarToggler">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
            <li class="nav-item">
                {% if request.user.is_authenticated %}
                <a class="nav-link"
                   href="{% url 'coffees:index' %}">
                    咖啡列表
                </a>
                {% endif %}
            </li>
        </ul>

        <ul class="navbar-nav mt-2 mt-lg-0">
            {% if request.user.is_authenticated %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">
                    登出 ( {{ request.user.username }} )
                </a>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">註冊</a>
            </li>
            <span class="navbar-text">
            /
          </span>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">登入</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/users/login.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>登入</h2>
        <hr>
        {% include 'share/_form.html' %}
        <br/>
    </div>
</div>
{% endblock %} 

templates/users/password_reset.html
{% extends 'layout.html' %}

{% block main %}
    <div class="row">
        <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
            <h2>忘記密碼</h2>
            <hr>
            {% include 'share/_form.html' %}
        </div>
    </div>
{% endblock %} 

templates/users/password_reset/email.html
會收到這封信是因為你通過以下網址 {{ site_name }} 要求重設你的帳戶密碼。

請透過下方連結進行重設:
{{ protocol }}://{{ domain }}{% url 'password_set' uidb64=uid token=token %}

順便提醒一下，這是你的用戶名 {{ user.get_username }}

感謝您使用本網站！

templates/users/password_set.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>設定密碼</h2>
        <hr>
        {% if validlink %}
        {% include 'share/_form.html' %}
        {% else %}
        <p>此連結已失效，請點<a href="{% url 'password_reset' %}">這裡</a>重新要求連結
        </p>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/users/register.html
{% extends 'layout.html' %}

{% block main %}
<div class="row">
    <div class="col col-sm-10 offset-sm-1 col-md-8 offset-md-2 col-lg-6 offset-lg-3">
        <h2>註冊</h2>
        <hr>
        {% include 'share/_form.html' %}
        <a href="{% url 'login' %}">已經有帳號了嗎？</a>
    </div>
</div>
{% endblock %}